
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import library.Connect;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sudhi
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBPrice = new javax.swing.JTextField();
        txtBId = new javax.swing.JTextField();
        txtBName = new javax.swing.JTextField();
        txtByear = new javax.swing.JTextField();
        txtBPub = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/isue.jpg"))); // NOI18N
        jLabel1.setText("Add Book Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, 460, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 115, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 115, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Publisher year");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 115, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Publisher");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 115, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 115, 33));

        txtBPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtBPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 183, 31));
        getContentPane().add(txtBId, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 183, 31));
        getContentPane().add(txtBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 183, 31));
        getContentPane().add(txtByear, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 183, 31));
        getContentPane().add(txtBPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 183, 31));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 82, 37));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 20, 44, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Login background.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1040, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPriceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if (txtBId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID field is required");
            txtBId.requestFocus();
        } else if (txtBName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name field is required");
            txtBName.requestFocus();
        } else if (txtBPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course field is required");
            txtBPrice.requestFocus();
        } else if (txtBPub.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semester field is required");
            txtBPub.requestFocus();
        } else if (txtByear.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Branch field is required");
            txtByear.requestFocus();
        }else {
            try {
                java.sql.Connection con = (java.sql.Connection) Connect.Connection();
                PreparedStatement pst = con.prepareStatement("INSERT INTO book(id,name,publisher,price,year,status) values(?,?,?,?,?,?)");
                pst.setString(1, txtBId.getText());
                pst.setString(2, txtBName.getText());
                pst.setString(3, txtBPub.getText());
                pst.setString(4, txtBPrice.getText());
                pst.setString(5, txtByear.getText());
                pst.setString(6, "NOT-ISSUED");

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Record Saved Successfully");
                txtBId.setText("");
                txtBName.setText("");
                txtBPub.setText("");
                txtBPrice.setText("");
                txtByear.setText("");

                pst.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBId;
    private javax.swing.JTextField txtBName;
    private javax.swing.JTextField txtBPrice;
    private javax.swing.JTextField txtBPub;
    private javax.swing.JTextField txtByear;
    // End of variables declaration//GEN-END:variables
}
